oras-project/oras-www

docs/index.md
This change adds simple documentation for the cache functionality added in https://github.com/deislabs/oras/pull/203
=> Add documentation for cache usage

docs/documentation/config.md
This doc applies to existing releases of `oras` CLI.
=> update doc for config push / pull

mkdocs.yml
Adding Trademark link for the Linux Foundation, per the CNCFwebsite guidelines in https://github.com/cncf/foundation/blob/master/website-guidelines.md as part of onboarding in https://github.com/cncf/toc/issues/692.
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>
=> Adding TM link

.github/workflows/oras-py-update.yaml
It does not look like we are going to get a bot (and access token) for the dispatch event anytime soon and I still want to make progress on getting the docs where they need to be, so I am adding a nightly dispatch that will currently open a PR, and when that works we can change to just push. If there are no changes it will not do anything, which is likely the most common case.
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> updating docs workflow for oras-py to be updated nightly

.github/workflows/oras-py-update.yaml
This PR will change the update to push directly instead of opening a PR, removing the need for human intervention. We can do this because the bot commits satisfy the DCO check.
I am also happy to review and merge changes from oras-py docs here manually (and if this is the preferred method please let me know and we will close this PR) but having a direct push means that we do not need that extra manual work. Note that I've also removed the repository dispatch (it won't be used) and changed the check from a comparison with HEAD to just looking for modified files (since we always will be on the main branch).
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> removing PR trigger and adding direct push on documentation change

docs/CLI/index.md
When releasing v0.13.0, we changed the suffix from tar.gz to zip so some windows user can user GUI unzip, but forget to update the doc.
=> Fix windows pack suffix

docs/implementors.md
This PR removes the deprecated `--media-type` flag in the user documentation.
=> fix: remove deprecated flags in doc

docs/implementors.md
Clicking the anchor link to the github relevant section https://oras.land/implementors/ seems broken
=> implementors.md: fix broken anchor link

docs/CLI/1_pushing.md, docs/CLI/3_manifest_config.md, docs/CLI/4_manifest_annotations.md, docs/Client_Libraries/1_python.md, docs/implementors.md
As per the [0.14 release notes](https://github.com/oras-project/oras/releases/tag/v0.14.0), breaking changes around `--manifest-config` and `--manifest-annotations` were introduced. This PR updates the docs to reflect the changes made.
- `--manifest-config` was updated to `--config` wherever an actual manifest config was used. If using an empty manifest config file, `--artifact-type` is used instead.
- `--manifest-annotations` was updated to `--annotation-file`
=> Update docs for breaking changes introduced in 0.14

docs/oras-go.md, docs/oras-go/v2.md, docs/oras.md
It appears these redirects are used for installation. Causing on my `go mod tidy` to fail after clearing cache:
`gotest.tools/v3/assert: oras.land/oras-go@v1.2.0: unrecognized import path "oras.land/oras-go": reading https://oras.land/oras-go?go-get=1: 404 Not Found`
Reverting these changes from https://github.com/oras-project/oras-www/pull/95
Signed-off-by: Terry Howe <tlhowe@amazon.com>
=> fix: revert missing redirects

CODEOWNERS
Add [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) based on the [OWNERS.md](https://github.com/oras-project/oras-www/blob/main/OWNERS.md) file.
=> chore: add CODEOWNERS based on OWNERS.md

LICENSE, mkdocs.yml
I don't think year is required on a copyright any longer.
=> fix: Remove old copyright year

docs/CLI/5_developer_guide.md
This PR introduces how should we cut off a release branch and call for vote, which should be applied to oras CLI 1.0.0 release.
=> doc: update release cut-off procedure

docs/CLI/6_reference_types.md, docs/blog/oras-0.15-a-fully-functional-registry-client.md
It seems that the `ghcr.io/oras-project/registry:v0.0.3-alpha`
image does not support the OCI reference type (referrers) API,
update to `ghcr.io/oras-project/registry:v1.0.0-rc.4` to fix it.
=> docs: fix distribution image

docs/CLI/2_pulling.md
This issue has merged, no need to mention it.
Closes: https://github.com/oras-project/oras-www/issues/44
Signed-off-by: Terry Howe <tlhowe@amazon.com>
=> fix: Remove reference to media-type option that was removed

CODEOWNERS, OWNERS.md
Hello @oras-project/oras-www-maintainers,
I have been actively contributing to this repository for the past three months. During this time, I have submitted [13 Pull Requests](https://github.com/oras-project/oras-www/pulls?q=is%3Apr+author%3Aasmitbm+), and 10 of them have been successfully merged. Additionally, I have designed the new [ORAS Website](https://oras.land) using Figma and contributed to its development. Recently, I was chosen as a mentor for two LFX projects within this repository (#65, #158). Furthermore, I have been assisting the maintainers by reviewing Pull Requests and helping newcomers in the community. Based on the [ORAS governance guide](https://github.com/oras-project/community/blob/main/governance/GOVERNANCE.md#subproject-owners), I believe I meet the qualifications …
=> doc: Nominate Asmit Malakannawar to be a subproject owner

docs/CLI_Reference/oras_blob_fetch.mdx
Closes: #130
By using jq and pv, one can show the content downloading progress when using ORAS. This demonstrates how to fetch a blob with a specific reference, determine its size using jq, and use pv to display the progress while redirecting the output to a file named layer.bin.
```
$ blob_ref=ghcr.io/oras-project/oras@sha256:74529e03eae02d1fff5c05e9a6ec2089e1f5ae96421169c29a7c165346e042e4
$ size=$(oras blob fetch --descriptor $blob_ref | jq -r .size)
$ oras blob fetch $blob_ref --output - | pv -s $size > layer.bin
```
=> updated oras_blob_fetch.mdx

.gitpod.yml, README.md
Added Gitpod support (Cloud IDE) for oras-www repository for one-click setup of our documentation website. Contributors can start contributing right away without worrying about system requirements.
=> feat: add gitpod support

docs/community/_category_.json, docs/community/community_resources.mdx, docs/community/contributing_guide.mdx, docs/community/developer_guide.mdx
This PR brings all community guides and resources under the "Community" section.
Fixes some issues from PR #202.
=> docs: restructure community guides and resources

docs/installation.mdx
This PR brings the introduction back on top, above the installation guide.
=> docs: change position of installation guide

docs/Tutorials/zot-registry-tutorial.mdx, docs/index.mdx, docusaurus.config.js, src/components/Header/index.jsx, src/components/ORAS_CLI/index.jsx
This PR updates all the links not working and renames "Tutorial" to "tutorial" for uniformity.
=> docs: fix broken links

.github/workflows/check_links.yml, docs/Tutorials/zot-registry-tutorial.mdx, docs/client_libraries/go.mdx, docs/community/community_resources.mdx, docs/index.mdx, package-lock.json, package.json
This adds a GitHub actions workflow which runs [remark validate links](https://github.com/remarkjs/remark-validate-links) which will check links in Markdown files in order to see if any are returning 404s. The logs will be available in each PR and Netlify as well.
I implemented the broken anchor links detection for both `npm start` and `npm run build`. So, even if we build this project locally, we'll get warnings there.
These are the key changes:
* Added the remark validate links for checking internal links, including checking that headers exist in linked-to files
* Added that internal link checker to the CI
* Edited a few docs which had incorrect links
Edit:
This is the log we'll get on each PR: https://github.com/oras-project/oras-www/actions/runs/5541071028/jobs/10113990367?pr=223#step: …
=> feat: add markdown link checker to validate links

docs/compatible_oci_registries.mdx
This PR renames the section `adopters` to `Compatible OCI Registries`.
=> docs: rename adopters

docs/how_to_guides/pushing_and_pulling.mdx
Closes #228
Resolves the 3 errors described in issue #228.
=> docs: resolves markdown error and misspells in "pushing and pulling artifacts" section

docs/how_to_guides/authentication.mdx
This PR adds a how-to guide for authenticating with OCI Registries.
It covers two methods:
1. Using `config.json`
2. Using docker credential helper
=> docs: Update guide to authenticate with OCI Registries

docs/concepts/artifact.mdx
As per the OCI call today this is makes the artifact decision much more simpler and we just have to set the artifact type  for OCI artifacts. 
Thanks to @dasiths
```mermaid
graph TD
HasBlob{Artifact has at least<br>one file or blob?}
HasConfigData{Artifact has additional<br> metadata config blob?}
Artifact_NoBlobs[Specify <b>artifactType</b>,<br>set config and layers<br>to empty descriptors.]
Artifact_NoConfig[Specify  <b>artifactType</b>, include<br>artifact in layers, set<br>config to empty descriptor.]
Artifact_WithConfig[Specify  <b>artifactType</b>,<br> specify config blob and mediaType,<br> include artifact in layers.]
HasBlob -- No --> Artifact_NoBlobs
HasBlob -- Yes --> HasConfigData
HasConfigData -- Yes --> Artifact_WithConfig
HasConfigData -- No --> Artifact_NoConfig
```
=> simplify decision tree for artifacts

docs/glossary.mdx
This PR adds a `Glossary` section in the documentation.
=> docs: add glossary

docs/how_to_guides/verifying_binaries.mdx, docs/installation.mdx
This PR brings the installation guide to the top level according to the new directory structure. 
It also fixes #69.
=> docs: update installation guide with validation for cli binaries

docs/client_libraries/go.mdx
1. Update supported `image-spec` version to `v1.1.0-rc5`.
2. Update supported `distribution-spec` version to `v1.1.0-rc3`.
Page preview: https://deploy-preview-273--oras-project.netlify.app/docs/client_libraries/go
=> docs: update supported spec version for Go SDK

docs/community/contributing_guide.mdx
Preview link - https://deploy-preview-249--oras-project.netlify.app/docs/community/contributing_guide#development-environment-setup
=> Recommend sembr for docs

docs/community/contributor_ladder.mdx
This PR adds a contributor ladder to the documentation.
=> docs: add contributor ladder

docs/commands/oras_attach.mdx
There is no such flag for `oras attach` in oras-CLI 1.1.0. This was probably removed after the proposed media-type was removed in OCI image-spec 1.1.0-rc4.
=> Remove example for "oras attach --image-spec ..."

src/components/JoinCommunity/community_links/styles.module.css, src/components/JoinCommunity/index.jsx, static/img/community_links/x.svg
Updated X logo in community links section
Prev: 
Current:
=> update x logo

blog/2024-05-29-oras-1.2.0-and-oras-go-2.5.0/index.mdx
Preview link: https://deploy-preview-325--oras-project.netlify.app/blog/oras-new-release
=> doc: add v1.2.0 blog post

docs/client_libraries/overview.mdx, docs/community/contributing_guide.mdx, docs/community/contributor_ladder.mdx, docs/community/reporting_security_concerns.mdx, docs/compatible_oci_registries.mdx, docs/concepts/artifact.mdx, docs/concepts/reference.mdx, docs/concepts/reftypes.mdx, docs/glossary.mdx, docs/how_to_guides/authentication.mdx, docs/how_to_guides/distributing_oci_layouts.mdx, docs/how_to_guides/manifest_config.mdx, docs/how_to_guides/pushing_and_pulling.mdx, docs/how_to_guides/verifying_binaries.mdx, docs/installation.mdx, docs/quickstart.mdx
With these files copied all over the place for every release, things like trailing spaces cause more diffs in PRs, so get rid of them all at once
=> chore: Remove all trailing spaces from files

docusaurus.config.js
I'm not entirely sure why these were broken before. Some other fix must have fixed them.
=> fix: Bring back broken footer links

versioned_docs/version-1.1/client_libraries/overview.mdx, versioned_docs/version-1.2/client_libraries/overview.mdx
Since it isn't clear right now what is going to be used for latest, I'd like to keep these synced up.
=> chore: update client library list for versioned docs

tools/install.sh, tools/refresh-commands.sh
Created a mapping file in case we need to use a bug fix release to generate the docs. I don't think that will happen often.
=> chore: update command generator for versioned docs

versioned_docs/version-1.1/commands/oras_attach.mdx, versioned_docs/version-1.1/commands/oras_cp.mdx, versioned_docs/version-1.1/commands/oras_discover.mdx, versioned_docs/version-1.1/commands/oras_help.mdx, versioned_docs/version-1.1/commands/oras_login.mdx, versioned_docs/version-1.1/commands/oras_logout.mdx, versioned_docs/version-1.1/commands/oras_pull.mdx, versioned_docs/version-1.1/commands/oras_push.mdx, versioned_docs/version-1.1/commands/oras_tag.mdx, versioned_docs/version-1.1/commands/oras_version.mdx, versioned_docs/version-1.1/how_to_guides/distributing_oci_layouts.mdx, versioned_docs/version-1.2/commands/oras_attach.mdx, versioned_docs/version-1.2/commands/oras_cp.mdx, versioned_docs/version-1.2/commands/oras_discover.mdx, versioned_docs/version-1.2/commands/oras_help.mdx, versioned_docs/version-1.2/commands/oras_login.mdx, versioned_docs/version-1.2/commands/oras_logout.mdx, versioned_docs/version-1.2/commands/oras_pull.mdx, versioned_docs/version-1.2/commands/oras_push.mdx, versioned_docs/version-1.2/commands/oras_resolve.mdx, versioned_docs/version-1.2/commands/oras_tag.mdx, versioned_docs/version-1.2/commands/oras_version.mdx, versioned_docs/version-1.2/how_to_guides/distributing_oci_layouts.mdx
Just ran the refresh script for 1.1 and 1.2. This is the same change that was merged in https://github.com/oras-project/oras-www/pull/319 but it is for 1.1 and 1.2.
Closes: https://github.com/oras-project/oras-www/issues/350
=> chore: Update command docs for 1.1 and 1.2

tools/parse.sh, versioned_docs/version-1.1/commands/oras_cp.mdx, versioned_docs/version-1.2/commands/oras_cp.mdx
Adding this argument to the read will preserve the `\` for the oras_copy documentation.  Another PR contains the documentation updates. The change results in this:
=> Preserve backslash

tools/refresh-commands.sh, versioned_docs/version-1.1/commands/oras_blob_delete.mdx, versioned_docs/version-1.1/commands/oras_blob_fetch.mdx, versioned_docs/version-1.1/commands/oras_blob_push.mdx, versioned_docs/version-1.1/commands/oras_manifest_delete.mdx, versioned_docs/version-1.1/commands/oras_manifest_fetch-config.mdx, versioned_docs/version-1.1/commands/oras_manifest_fetch.mdx, versioned_docs/version-1.1/commands/oras_manifest_push.mdx, versioned_docs/version-1.1/commands/oras_repo_ls.mdx, versioned_docs/version-1.1/commands/oras_repo_tags.mdx, versioned_docs/version-1.2/commands/oras_blob_delete.mdx, versioned_docs/version-1.2/commands/oras_blob_fetch.mdx, versioned_docs/version-1.2/commands/oras_blob_push.mdx, versioned_docs/version-1.2/commands/oras_manifest_delete.mdx, versioned_docs/version-1.2/commands/oras_manifest_fetch-config.mdx, versioned_docs/version-1.2/commands/oras_manifest_fetch.mdx, versioned_docs/version-1.2/commands/oras_manifest_push.mdx, versioned_docs/version-1.2/commands/oras_repo_ls.mdx, versioned_docs/version-1.2/commands/oras_repo_tags.mdx
There were several simultaneous PRs and it made it difficult to detect these errors in subcommand generation.
* The list command for subcommands needed an argument
* The directory was wrong for subcommands
* Logic was backwards on detecting subcommands
* Was not actually updating the subcommands in versioned_docs
=> fix: Subcommand generation was broken for versioned docs

versioned_docs/version-1.2/how_to_guides/format_output.mdx
Add formatted output user manual. Most of the content is replicated from the [spec](https://github.com/oras-project/oras/blob/main/docs/proposals/formatted-output.md#proposal-and-desired-user-experience) because those examples are also helpful to end users. 
Preview link: https://deploy-preview-356--oras-project.netlify.app/docs/how_to_guides/format_output
=> doc: add formatted output user manual

tools/parse_main.sh, tools/refresh-commands.sh, versioned_docs/version-1.1/commands/use_oras_cli.mdx, versioned_docs/version-1.2/commands/use_oras_cli.mdx
Generate the main commands page.
=> chore: Generate main commands page

versioned_docs/version-1.2/how_to_guides/go_script.mdx
Update the go script documentation for stdout capture. This works for 1.2, but stderr capture is not part of 1.2.
=> chore: Update go script for data capture

versioned_docs/version-1.2/how_to_guides/remote_registries.mdx, versioned_docs/version-1.2/quickstart.mdx
I was going to revive [Deepesha's PR ](https://github.com/oras-project/oras-www/pull/252) on this, but with the merge conflicts and changes required, it was too far off. This PR adds documentation on how to use a remote registry with ORAS.
Closes: https://github.com/oras-project/oras-www/pull/252
=> feat: add documentation about remote registries

netlify.toml
Redirects from old /docs/community to new /community
Closes: https://github.com/oras-project/oras-www/issues/348
https://deploy-preview-388--oras-project.netlify.app/docs/community/community_resources
redirects to 
https://deploy-preview-388--oras-project.netlify.app/community/community_resources
=> fix: redirect for community page

.github/workflows/vale.yaml
Add vale github action
Does not block PRs now https://github.com/oras-project/oras-www/actions/runs/10852551086/job/30118842300?pr=392 but reports errors.
Closes: https://github.com/oras-project/oras-www/issues/113
=> chore: add github action for vale

versioned_docs/version-1.2/compatible_oci_registries.mdx
At my day job, we use Artifactory and have started to use it as an OCI registry.  When researching this, it was not clear `oras` supported Artifactory.  This PR is to update the applicable documentation.
Closes #393.
Closes #205.
=> Add Artifactory as a Compatible OCI Registry

.github/workflows/vale.yaml
Related: https://github.com/errata-ai/vale-action/issues/128
```
Ensuring core python and ruby dependencies are present
/usr/bin/pip install docutils
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See …
```
=> fix: vale working on ubuntu-latest

blog/2024-05-29-oras-1.2.0-and-oras-go-2.5.0/index.mdx
Gets rid of this warning:
```
[WARNING] Docusaurus found blog posts without truncation markers:
- "blog/2024-05-29-oras-1.2.0-and-oras-go-2.5.0/index.mdx"
We recommend using truncation markers (`` or `{/* truncate */}`) in blog posts to create shorter previews on blog paginated lists.
Tip: turn this security off with the `onUntruncatedBlogPosts: 'ignore'` blog plugin option.
```
=> fix: resolves make truncate warning

src/components/CommunityLogos/styles.module.css
=> style: enhance marquee behavior

versioned_docs/version-1.2/compatible_oci_registries.mdx
add Harbor as a compatible registry to the registry list
=> doc: add Harbor as a compatible registry

package-lock.json, package.json
The packages preset-classic and theme-mermaid require exact docusaurus/core version match.
This PR will make PRs like https://github.com/oras-project/oras-www/pull/422 unnecessary.
=> chore: avoid dependabot conflict with docusaurus core package

versioned_docs/version-1.2/installation.mdx
Update installation guide to v1.2.1 as the vote is passed in https://github.com/oras-project/oras/pull/1563
=> doc: update installation guide to v1.2.1

tools/install.sh, tools/list_commands.sh, tools/parse.sh, tools/refresh-commands.sh, tools/subcommands.sh
The current command document generator only does two levels of commands. The introduction of `oras manifest index create` is three levels. While this PR is a bit tough to look at, the actual code is a lot easier to look at.
* Broke out `list_command.sh` into a shell script that can be run and tested by itself for example `./tools/list_command manifest index`
* Simplified the path to the current `oras` command so it doesn't need to be passed around
* Simplified temp file handling
* Created `subcommands.sh` that either prints the command or iterates through the subcommands which can be run for example `./tools/subcommands.sh manifest ./versioned_docs/version-1.3.0-beta.1/commands `
=> fix: allow lower level subcommands

versioned_docs/version-1.3.0-beta.1/installation.mdx
I realized I'd never updated the installation page.
=> fix: v1.3.0-beta.1 install page

versioned_docs/version-1.2/compatible_oci_registries.mdx
As  the documentation uses the `$` prefix in the command  here https://github.com/oras-project/oras-www/blob/4e73bda9c69b1a31c0ddd345f01b35c0249b763e/versioned_docs/version-1.2/compatible_oci_registries.mdx?plain=1#L89-L93
Which causes an error while using the terminal, After adding a separator it works fine...
=> fix: Formatting Issue on doc

vale/config/vocabularies/oras/accept.txt
There were a bunch of warnings before, with this:
```
Run errata-ai/vale-action@v2
with:
files: ["community", "versioned_docs"]
debug: true
fail_on_error: true
reporter: github-pr-check
version: latest
level: error
filter_mode: added
token: ***
env:
GITHUB_TOKEN: ***
Installing Vale version 'latest' ...
/usr/bin/tar xz --overwrite --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/work/_temp/74[2](https://github.com/oras-project/oras-www/actions/runs/12521551653/job/34928761208?pr=444#step:4:2)f37cc-54e7-4[3](https://github.com/oras-project/oras-www/actions/runs/12521551653/job/34928761208?pr=444#step:4:3)57-84ec-86e4523d93fb
Installed version '3.9.2' into '/home/runner/vale'.
Installing ReviewDog version '0.17.0' ...
/usr/bin/tar xz --overwrite …
```
=> Allow two github spellings

versioned_docs/version-1.2/client_libraries/java.mdx, versioned_docs/version-1.2/client_libraries/overview.mdx, versioned_docs/version-1.3.0-beta.1/client_libraries/java.mdx, versioned_docs/version-1.3.0-beta.1/client_libraries/overview.mdx
Include in progress java library
Not sure on which version it should be added
The snapshot link goes to the SNAPSHOT package built from main (since we don't have release yet)
=> feature: Include java page

vale/config/vocabularies/oras/accept.txt
Lower case `powershell` is used by the completion command.
=> fix: Add PowerShell to acceptable spellings

versioned_docs/version-1.1/how_to_guides/verifying_binaries.mdx, versioned_docs/version-1.2/how_to_guides/verifying_binaries.mdx, versioned_docs/version-1.3.0-beta.1/how_to_guides/verifying_binaries.mdx
Update the validation documentation to allow multiple GPG keys
Related https://github.com/oras-project/oras/issues/1595
=> fix: update the validation documentation for gpg keys

versioned_docs/version-1.3.0-beta/how_to_guides/multiarch.mdx
Add a how-to guilde for multiple architecture artifact management.
Closes: https://github.com/oras-project/oras-www/issues/247
=> feat: add how-to for multiple architecture

versioned_docs/version-1.3.0-beta/how_to_guides/multiarch.mdx
The environment variable makes this a little more clear here.
Closes: https://github.com/oras-project/oras-www/issues/464
=> Use environment variable for multi-architecture digest

src/theme/DocVersionBanner/index.js
This pull request includes a minor update to the `DocVersionBanner` component. The change updates the link for the stable release documentation to point to the `/docs` endpoint instead of `/docs/latest`.
Fixes #471
=> fix: update link for latest documentations

versioned_docs/version-1.3.0-beta/client_libraries/go.mdx
1. Update supported spec version to `v1.1.1`
2. Replace the "Usage" and "Quick Start" section with a "Getting Started" section
Page preview: https://deploy-preview-473--oras-project.netlify.app/docs/1.3.0-beta/client_libraries/go
=> docs: update documentation for Go SDK

blog/2025-04-28-oras-1.3.0-beta.3/index.mdx
The 1.3.0-beta.3 page should have truncate for preview
=> fix: add truncate for page preview

vale/config/vocabularies/oras/accept.txt, versioned_docs/version-1.3.0-beta/how_to_guides/backup-restore.mdx
Add a user guidance for `oras backup` and `oras restore` to v1.3.0-beta.4.
Preview link: https://deploy-preview-481--oras-project.netlify.app/docs/1.3.0-beta/how_to_guides/backup-restore
=> docs: add a user guidance for oras backup and oras restore
