docs/index.md

Reverts oras-project/oras-www#1
As explained in https://github.com/oras-project/oras-www/issues/6

Revert "Add documentation for cache usage"

---

docs/index.md

Fixes #6
This change adds simple documentation for the cache functionality added in https://github.com/deislabs/oras/pull/203

Ad documentation for cache usage

---

LICENSE

Actioning as part of onboarding to CNCF
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

Update LICENSE to Apache v2

---

docs/blog/index.md
docs/blog/oras-artifacts-draft-specification-release.md
docs/blog/oras-artifacts-draft-specification-release/net-monitor-graph.svg

Adding blog category and blog post authored by @SteveLasker.
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

Adding blog and blog post

---

docs/CLI/6_reference_types.md
docs/assets/images/net-monitor-graph.svg

Add docs for how to use preview ORAS builds to push and discover ORAS Artifacts
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

Add ORAS Artifact Reference Types docs

---

docs/CLI/6_reference_types.md

Small nit, official public name is `Amazon ECR`. Thanks!

Updating AWS ACR => Amazon ECR

---

docs/CLI/5_developer_guide.md

Since releasing is update in oras-go/oras#377, this PR updated the checklist.
Resolves #10

Update release check list

---

docs/CLI/5_developer_guide.md

Fix typo in release check list

---

docs/CLI/index.md

Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>
Fix: https://github.com/oras-project/oras-www/issues/35

refine ORAS CLI installation guide

---

docs/CLI/index.md

Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>
Fix: https://github.com/oras-project/oras-www/issues/38

update the installation guide to 0.13

---

docs/implementors.md

Remove https in the pull doc

---

docs/CLI/5_developer_guide.md
docs/CLI/index.md

doc: update for 0.14.0

---

docs/CLI/5_developer_guide.md
docs/CLI/index.md

chore: update version number to 0.14.1

---

docs/blog/index.md
docs/blog/oras-0.14-and-future.md

There is a broken link in the blog post, and the blog post index is not auto-generated. This PR corrects both issues.
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

Typo fixes for blog post

---

docs/CLI/5_developer_guide.md
docs/CLI/index.md
docs/blog/oras-0.14-and-future.md

doc: update to 0.15.0 release

---

docs/blog/oras-0.14-and-future.md

fix: revert changes in 0.14 blog markdown

---

docs/implementors.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
/cc @FeynmanZhou

doc: add docker hub to implementors

---

docs/implementors.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

doc: add new implementors

---

README.md

Signed-off-by: Amishakumari544 <amishakumari544@gmail.com>
This PR fixes #91

fix: update the README with the latest installation guide

---

docs/blog/gatekeeper-policies-as-oci-image.md
docs/blog/index.md

Signed-off-by: Mathieu Benoit <mathieu-benoit@hotmail.fr>
Minor fixes for the gatekeeper post.

Minor fixes for the gatekeeper post

---

docs/CLI_Reference/index.md

This link was broken.
Signed-off-by: Terry Howe <tlhowe@amazon.com>

fix: Fix broken blob push link

---

README.md

docs: Make the README a bit better

---

requirements.txt

Update mkdocs and other requirements. This has got to resolve some CVEs.

chore: Update mkdocs and other requirements

---

docs/implementors.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
/cc @FeynmanZhou @rchincha

add zot registry

---

docs/implementors.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
/cc @FeynmanZhou

add notation

---

docs/implementors.md

add awslabs soci snapshotter

---

docs/Client_Libraries/0_go.md

doc(go): improve SDK quick start

---

docs/contributing.md

This is a start at least.
Partial: https://github.com/oras-project/oras/issues/780

feat: Add contributing document

---

docs/CLI/index.md

Confirmed on linux/amd64 and windows/amd64

doc: update installation guide for 1.0.0-rc.2

---

docs/CLI/index.md

Confirm zsh, bash on linux/amd64 and window/amd64 cmd shell.

update installation script with version variable

---

docs/CLI/index.md

This PR updates the installation doc. Validated Windows and Linux amd64 installation.

chore: update installation doc for 1.0.0 release

---

docs/CLI/index.md

add oras installation instructions from Nixpkgs

---

docusaurus.config.js
src/css/custom.css

Add Algolia search box to the website and css variables, if we want to change the apperance of the searchbox in future.

feat: add algolia search box

---

docs/Client_Libraries/go.mdx

doc: add example for pulling images via oras-go

---

.github/dependabot.yml

Closes: #152
This pull request Resolves Issue #152 
Added dependabot.yml

Resolved #152 Added dependabot.yml

---

docs/CLI/pulling.mdx
docs/CLI/pushing.mdx

Fix #182: fix some typos in doc files

---

docs/CLI/installation.mdx

This PR add the new way of installing oras

Explain how to install oras snap

---

docs/CLI/_category_.json
docs/CLI_Reference/_category_.json
docs/Client_Libraries/_category_.json
docs/adopters.mdx
docs/community.mdx
docs/contributing.mdx
docs/index.mdx

This PR updates all the sidebar positions to make it easy to rearrange the categories according to our requirements.

docs: update sidebar positions

---

README.md

Added The Licenses badge
And a contribution section takes the user to community page
Closes #211

[Docs] Added the Licenses badge and small "Contribution" section to readme

---

docs/commands/oras_login.mdx

[chore] add docs for oras_login --resolve flag

---

docs/how_to_guides/manifest_annotations.mdx

This PR adds commands to add annotations while pushing or attaching artifacts.

docs: update manifest annotations

---

docs/how_to_guides/manifest_annotations.mdx
docs/how_to_guides/pushing_and_pulling.mdx

adding `oras manifest fetch` to the docs "Pushing_and_pulling"

---

docs/commands/oras_attach.mdx
docs/commands/oras_blob_delete.mdx
docs/commands/oras_blob_fetch.mdx
docs/commands/oras_blob_push.mdx
docs/commands/oras_copy.mdx
docs/commands/oras_discover.mdx
docs/commands/oras_login.mdx
docs/commands/oras_logout.mdx
docs/commands/oras_manifest_delete.mdx
docs/commands/oras_manifest_fetch-config.mdx
docs/commands/oras_manifest_fetch.mdx
docs/commands/oras_manifest_push.mdx
docs/commands/oras_pull.mdx
docs/commands/oras_push.mdx
docs/commands/oras_repo_ls.mdx
docs/commands/oras_repo_tags.mdx
docs/commands/oras_tag.mdx
docs/commands/oras_version.mdx

This PR changes the sidebar positions (without changing the current order) so we can add commands to the list easily as we introduce new ones.

docs: change sidebar positions for commands

---

docs/installation.mdx

This PR updates installation version to 1.0.1

doc: update to 1.0.1 installation

---

.github/workflows/check_links.yml

Fix the issue of the lint check workflow as we encountered in https://github.com/oras-project/oras-www/pull/257#issuecomment-1705902017

fix: uprade actions/checkout to fix lint check workflow issue

---

docusaurus.config.js

Fix #260 .
Preview: https://deploy-preview-261--oras-project.netlify.app/

chore: update site version to v1.1.0

---

src/components/ORAS_CLI/index.jsx

Update download version to 1.1.0

---

docs/quickstart.mdx

This PR updates the format of the guide and removes the word phase.
cc: @FeynmanZhou

docs: update format of quick start guide

---

.github/workflows/check_links.yml

Update node action to v4

---

docs/commands/oras_attach.mdx
docs/commands/oras_discover.mdx
docs/commands/oras_login.mdx
docs/commands/oras_logout.mdx
docs/commands/oras_pull.mdx
docs/commands/oras_push.mdx
docs/commands/oras_tag.mdx
docs/commands/oras_version.mdx

Working on generating these documents. This PR just synchronizes from the CLI repository.
Partial: https://github.com/oras-project/oras-www/issues/287

chore: syncrhonize CLI text with documentation

---

package-lock.json
package.json

Closes: https://github.com/oras-project/oras-www/pull/313
Closes: https://github.com/oras-project/oras-www/pull/305
Closes: https://github.com/oras-project/oras-www/pull/303
Closes: https://github.com/oras-project/oras-www/pull/302

chore: Update docusaurus if they need to be updated together

---

Makefile

All the other repos have a Makefile and so I often am running make here.

chore: Add Makefile for consistency

---

docs/compatible_oci_registries.mdx

Updated artifact guidance link to the longterm documentation

Updated artifact guidance link

---

package-lock.json
package.json

Closes: #332 
Closes: #331 
Closes: #330 
Closes: #329

chore: update docusaurus all at once

---

docs/client_libraries/overview.mdx

docs: Added reference to oras-dotnet API docs

docs: Added reference to oras-dotnet API docs

---

versioned_docs/version-1.2/client_libraries/rust.mdx

-  @thomastaylor312 I'm just updateing the placeholders here. We can enhance the docs going forward. 
Preview - https://deploy-preview-355--oras-project.netlify.app/docs/client_libraries/rust

docs: update rust client

---

versioned_docs/version-1.1/how_to_guides/go_script.mdx
versioned_docs/version-1.2/how_to_guides/go_script.mdx

Closes: https://github.com/oras-project/oras-www/issues/357

chore: Mark go scripting experimental

---

tools/parse.sh

Generates the same documentation, less code.

chore: Clean up the tools parse.sh script

---

community/contributing_guide.mdx
community/developer_guide.mdx
community/reporting_security_concerns.mdx
versioned_docs/version-1.1/client_libraries/overview.mdx
versioned_docs/version-1.1/commands/oras_completion_bash.mdx
versioned_docs/version-1.1/compatible_oci_registries.mdx
versioned_docs/version-1.1/concepts/artifact.mdx
versioned_docs/version-1.1/concepts/reference.mdx
versioned_docs/version-1.1/concepts/reftypes.mdx
versioned_docs/version-1.1/how_to_guides/manifest_annotations.mdx
versioned_docs/version-1.1/how_to_guides/pushing_and_pulling.mdx
versioned_docs/version-1.2/client_libraries/overview.mdx
versioned_docs/version-1.2/commands/oras_completion_bash.mdx
versioned_docs/version-1.2/compatible_oci_registries.mdx
versioned_docs/version-1.2/concepts/artifact.mdx
versioned_docs/version-1.2/concepts/reference.mdx
versioned_docs/version-1.2/concepts/reftypes.mdx
versioned_docs/version-1.2/how_to_guides/manifest_annotations.mdx
versioned_docs/version-1.2/how_to_guides/pushing_and_pulling.mdx
versioned_docs/version-1.2/how_to_guides/remote_registries.mdx

I ran vale on the source mdx files and detected a few spelling errors
Partial: https://github.com/oras-project/oras-www/issues/113

fix: spelling errors detected by vale

---

netlify.toml

netlify was not supporting v20 all of the sudden.

chore: update node to v21

---

CONTRIBUTING.md

Add a CONTRIBUTING.md file to the repository that references the web page. The file was copied from `oras`
Closes: https://github.com/oras-project/oras-www/issues/100

chore: add CONTRIBUTING.md file to repository

---

package-lock.json
package.json

Resolves several vulnerabilities to docusaurus and othere packages.
After:
```
% make
npm install
up to date, audited 1389 packages in 970ms
342 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
npm run build
```
Closes: https://github.com/oras-project/oras-www/pull/415
Closes: https://github.com/oras-project/oras-www/pull/414
Closes: https://github.com/oras-project/oras-www/pull/411

fix: resolves 5 vulnerabilities 2 low and 3 high

---

package-lock.json
package.json

Closes: https://github.com/oras-project/oras-www/pull/419
Closes: https://github.com/oras-project/oras-www/pull/418
Closes: https://github.com/oras-project/oras-www/pull/417

chore: update docusaurs for cves again

---

.github/dependabot.yml

Hopefully this will resolve the dependabot docusaurus issues.

fix: dependabot grouping to fix docusaurus updates

---

versioned_docs/version-1.2/installation.mdx

update oras CLI version to v1.2.2

doc: update oras CLI version to v1.2.2

---

versioned_docs/version-1.3.0-beta.1/installation.mdx

Added some generic installation instructions to help people determine OS and ARCH

feature: help determine os and arch

---

package-lock.json

I guess dependabot didn't go far enough, but this seems to work

Patch the latest npm vulnerabilities

---

src/theme/DocVersionBanner/index.js
versioned_docs/version-1.3.0-beta/installation.mdx

Updated the banner and installation page to reflect the latest changes in the project.

doc: update banner and installation page

---

versioned_docs/version-1.2/client_libraries/java.mdx
versioned_docs/version-1.3.0-beta/client_libraries/java.mdx

- Link to latest javadoc
- Link to Maven central
- Link to push/pull artifacts to readme

Update ORAS Java documentation

---

static/adopters/data.js

Hello! 👋 
Thank you for the previous issue merge. :) 🙇 Much appreciated.
I would like to slightly improve the name to extend it to the full name instead of the acronym. Just to make it more clear and distinct. :) Thank you!

fix: modify ocm name to its full name

---

package-lock.json

I don't know why dependabbot doesn't do more of this

chore: fix some vulnerabilities
